package com.unit.testing;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * This is the test generated by default.
 * 
 * @author JulioPachecoSanginez
 *
 */
@SpringBootTest
class PruebasUnitariasApplicationTest {

  /**
   * Put something here.
   */
  @Test
  void contextLoads() {}

}
